//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPD.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeakerLike
    {
        public long LikeId { get; set; }
        public int SpeakerId { get; set; }
        public System.DateTime OccuredAt { get; set; }
    
        public virtual Speaker Speaker { get; set; }
    }
}
